spring:
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASS}
    name: union notes

  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update

server:
  address: 0.0.0.0
  port: ${PORT}
