spring:
  profiles:
    active: prod
  datasource:
    url: jdbc:postgresql://${PROD_DB_HOST}:${PROD_DB_PORT}/${PROD_DB_NAME}
    username: ${PROD_DB_USER}
    password: ${PROD_DB_PASS}
    name: union notes
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    locations: classpath:db.migration
    baseline-on-migrate: false
    baseline-version: 0
    clean-disabled: false
security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 3600000
