services:
  postgres:
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=union_notes"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_USER=taaz"
    ports:
      - "5432:5432"
  app:
    image: union_notes
    environment:
      - PROD_DB_HOST=${PROD_DB_HOST}
      - PROD_DB_PORT=${PROD_DB_PORT}
      - PROD_DB_NAME=${PROD_DB_NAME}
      - PROD_DB_USER=${PROD_DB_USER}
      - PROD_DB_PASS=${PROD_DB_PASS}
